compile: &defaults
  build: .
  environment:
    RUBY_VERSION:
    OPENSSL_VERSION:
  command: rake compile
test:
  <<: *defaults
  command: rake compile test OSSL_MDEBUG=1 -- --enable-debug
debug:
  <<: *defaults
  command: /bin/bash
